name: ce-portal

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ce-portal-app
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      PHP_FPM_USER: www-data
      PHP_FPM_GROUP: www-data
      # Drivers
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file # -> database
      FILESYSTEM_DRIVER: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      # Access
      ADMIN_REQUIRES_2FA: false
      CHANGE_EMAIL: false
      ENABLE_REGISTRATION: false
      PASSWORD_HISTORY: 3
      SINGLE_LOGIN: false
      PASSWORD_EXPIRES_DAYS: 180
    volumes:
      - app:/var/www/html
    networks:
      - appnet

  queue:
    image: ce-portal-app
    depends_on:
      - app
    env_file:
      - .env
    command:
      ["php", "artisan", "queue:work", "--sleep=3", "--tries=3", "--timeout=90"]
    restart: unless-stopped
    networks:
      - appnet

  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - app:/var/www/html:ro
    networks:
      - appnet

  db:
    image: mysql:8.0
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "3307:3306" # Expose MySQL port to outside for development purposes with non default port
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

volumes:
  app:
  db_data:

networks:
  appnet:
    driver: bridge
